### ISSUE TITLE
Page Preloading Status Indicator

### ISSUE THREAD

**Issue by daronyondem** [XomniCloud/xomni-cms-vnext#45]
There is no indication about the status of a page during initial lunch. There is no way to figure out if a page is downloading some data in the back-end or not. This causes a page to open with empty input controls at first and than spontaneously populate the data.

**Comment by ilkayilknur** [comment]
We open a loading modal dialog with progress indicator on page loads. Maybe, you haven't seen it yet because of the https://github.com/XomniCloud/xomni-cms-vnext/issues/42 issue. Is it enough for you ?
![untitled](https://cloud.githubusercontent.com/assets/5785927/7685301/fef686a0-fd95-11e4-87f7-72e66d04d1af.png)

**Comment by daronyondem** [comment]
Might be. Let me know when I should give another round of test. Thanks

**Comment by gokhangulbiz** [comment]
Fixed 0169d01.
